--creo una bd en mi cuenta y ahi creo la vista apuntando a la bd de amazon
CREATE OR REPLACE DATABASE CARLOS_SANDBOX;
CREATE OR REPLACE SCHEMA CARLOS_SANDBOX.DATAFEEDS;

--sacando cuantos nulos hay en cada columna
SELECT
  COUNT(*) AS total_filas,

  SUM(IFF(SITE IS NULL, 1, 0)) AS null_site,
  SUM(IFF(COUNTRY IS NULL, 1, 0)) AS null_country,
  SUM(IFF(YEAR IS NULL, 1, 0)) AS null_year,
  SUM(IFF(MONTH IS NULL, 1, 0)) AS null_month,
  SUM(IFF(PRODUCT IS NULL, 1, 0)) AS null_product,
  SUM(IFF(TITLE IS NULL, 1, 0)) AS null_title,
  SUM(IFF(BRAND IS NULL, 1, 0)) AS null_brand,
  SUM(IFF(MAIN_CATEGORY IS NULL, 1, 0)) AS null_main_category,
  SUM(IFF(SUB_CATEGORY IS NULL, 1, 0)) AS null_sub_category,
  SUM(IFF(ESTIMATED_VIEWS IS NULL, 1, 0)) AS null_estimated_views,
  SUM(IFF(ESTIMATED_PURCHASES IS NULL, 1, 0)) AS null_estimated_purchases
FROM amazon_and_ecommerce_websites_product_views_and_purchases.datafeeds.product_views_and_purchases;

--creando la vista
CREATE OR REPLACE VIEW CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_CLEAN AS
SELECT
  SITE,
  COUNTRY,
  YEAR,
  MONTH,
  PRODUCT,

  /* Textos */
  COALESCE(TITLE, 'NO TITLE') AS TITLE,
  COALESCE(BRAND, 'UNKNOWN') AS BRAND,
  COALESCE(MAIN_CATEGORY, 'UNKNOWN') AS MAIN_CATEGORY,
  COALESCE(SUB_CATEGORY, 'UNKNOWN') AS SUB_CATEGORY,

  /* Métricas */
  COALESCE(ESTIMATED_VIEWS, 0) AS ESTIMATED_VIEWS,
  COALESCE(ESTIMATED_PURCHASES, 0) AS ESTIMATED_PURCHASES

FROM AMAZON_AND_ECOMMERCE_WEBSITES_PRODUCT_VIEWS_AND_PURCHASES.DATAFEEDS.PRODUCT_VIEWS_AND_PURCHASES;

--corroboramos que funcione este metodo de crear una bd y apuntar a la de amazon 
SELECT *
FROM CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_CLEAN
LIMIT 20;

--comprobando que la vista haya funcionado
SELECT
  COUNT(*) AS total_filas,

  SUM(IFF(SITE IS NULL, 1, 0)) AS null_site,
  SUM(IFF(COUNTRY IS NULL, 1, 0)) AS null_country,
  SUM(IFF(YEAR IS NULL, 1, 0)) AS null_year,
  SUM(IFF(MONTH IS NULL, 1, 0)) AS null_month,
  SUM(IFF(PRODUCT IS NULL, 1, 0)) AS null_product,

  SUM(IFF(TITLE IS NULL, 1, 0)) AS null_title,
  SUM(IFF(BRAND IS NULL, 1, 0)) AS null_brand,
  SUM(IFF(MAIN_CATEGORY IS NULL, 1, 0)) AS null_main_category,
  SUM(IFF(SUB_CATEGORY IS NULL, 1, 0)) AS null_sub_category,

  SUM(IFF(ESTIMATED_VIEWS IS NULL, 1, 0)) AS null_views,
  SUM(IFF(ESTIMATED_PURCHASES IS NULL, 1, 0)) AS null_purchases
FROM CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_CLEAN;


--validadno que los valores se hayan sustituido
SELECT
  TITLE,
  BRAND,
  MAIN_CATEGORY,
  SUB_CATEGORY,
  COUNT(*) AS registros
FROM CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_CLEAN
WHERE TITLE = 'NO TITLE'
   OR BRAND = 'UNKNOWN'
   OR MAIN_CATEGORY = 'UNKNOWN'
   OR SUB_CATEGORY = 'UNKNOWN'
GROUP BY 1,2,3,4
ORDER BY registros DESC
LIMIT 20;

SELECT
  COUNT(*) AS filas_con_views_0
FROM CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_CLEAN
WHERE ESTIMATED_VIEWS = 0;

SELECT
  COUNT(*) AS filas_con_purchases_0
FROM CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_CLEAN
WHERE ESTIMATED_PURCHASES = 0;

SELECT COUNT(*) AS casos_anomalos
FROM CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_CLEAN
WHERE ESTIMATED_PURCHASES > ESTIMATED_VIEWS;

SELECT
  (SELECT COUNT(*) 
   FROM AMAZON_AND_ECOMMERCE_WEBSITES_PRODUCT_VIEWS_AND_PURCHASES.DATAFEEDS.PRODUCT_VIEWS_AND_PURCHASES) AS filas_raw,

  (SELECT COUNT(*) 
   FROM CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_CLEAN) AS filas_clean;


--detectando duplicados logicos
 SELECT
  SITE,
  COUNTRY,
  YEAR,
  MONTH,
  PRODUCT,
  COUNT(*) AS veces
FROM CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_CLEAN
GROUP BY SITE, COUNTRY, YEAR, MONTH, PRODUCT
HAVING COUNT(*) > 1
ORDER BY veces DESC;
  
--creando una vista sin duplicado
CREATE OR REPLACE VIEW CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_DEDUP AS
SELECT
  SITE,
  COUNTRY,
  YEAR,
  MONTH,
  PRODUCT,

  /* Atributos: tomamos uno representativo */
  ANY_VALUE(TITLE) AS TITLE,
  ANY_VALUE(BRAND) AS BRAND,
  ANY_VALUE(MAIN_CATEGORY) AS MAIN_CATEGORY,
  ANY_VALUE(SUB_CATEGORY) AS SUB_CATEGORY,

  /* Métricas: se agregan */
  SUM(ESTIMATED_VIEWS) AS ESTIMATED_VIEWS,
  SUM(ESTIMATED_PURCHASES) AS ESTIMATED_PURCHASES

FROM CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_CLEAN
GROUP BY SITE, COUNTRY, YEAR, MONTH, PRODUCT;

--comprobando que no hay duplciados
SELECT
  SITE,
  COUNTRY,
  YEAR,
  MONTH,
  PRODUCT,
  COUNT(*) AS veces
FROM CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_DEDUP
GROUP BY SITE, COUNTRY, YEAR, MONTH, PRODUCT
HAVING COUNT(*) > 1;

--comparando entre vistas
SELECT
  (SELECT COUNT(*) FROM CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_CLEAN) AS filas_clean,
  (SELECT COUNT(*) FROM CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_DEDUP) AS filas_dedup;

--detectando las anomalias
SELECT
  COUNT(*) AS total_anomalias
FROM CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_DEDUP
WHERE ESTIMATED_PURCHASES > ESTIMATED_VIEWS;

--ver ejemplos de las anomalias
SELECT
  SITE,
  COUNTRY,
  YEAR,
  MONTH,
  PRODUCT,
  ESTIMATED_VIEWS,
  ESTIMATED_PURCHASES
FROM CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_DEDUP
WHERE ESTIMATED_PURCHASES > ESTIMATED_VIEWS
ORDER BY (ESTIMATED_PURCHASES - ESTIMATED_VIEWS) DESC
LIMIT 20;


--vista con anomalias tratadas
CREATE OR REPLACE VIEW CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_FINAL AS
SELECT
  SITE,
  COUNTRY,
  YEAR,
  MONTH,
  PRODUCT,
  TITLE,
  BRAND,
  MAIN_CATEGORY,
  SUB_CATEGORY,

  /* Views se mantienen */
  ESTIMATED_VIEWS,

  /* Regla de anomalía */
  CASE
    WHEN ESTIMATED_PURCHASES > ESTIMATED_VIEWS
      THEN ESTIMATED_VIEWS
    ELSE ESTIMATED_PURCHASES
  END AS ESTIMATED_PURCHASES,

  /* Flag de anomalía */
  CASE
    WHEN ESTIMATED_PURCHASES > ESTIMATED_VIEWS
      THEN 1
    ELSE 0
  END AS IS_ANOMALY

FROM CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_DEDUP;

--validar que los cambios se hayan aplicado
SELECT COUNT(*) AS anomalias_restantes
FROM CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_FINAL
WHERE ESTIMATED_PURCHASES > ESTIMATED_VIEWS;

--ver cuantos registros fueron corregidos
SELECT
  COUNT(*) AS registros_corregidos
FROM CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_FINAL
WHERE IS_ANOMALY = 1;


-- crear tabla final (materializacion)
CREATE OR REPLACE TABLE CARLOS_SANDBOX.DATAFEEDS.DATASET_FINAL AS
SELECT *
FROM CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_FINAL;

--validando que la tabla existe
SHOW TABLES IN SCHEMA CARLOS_SANDBOX.DATAFEEDS;

--verificando numero de filas
SELECT COUNT(*) 
FROM CARLOS_SANDBOX.DATAFEEDS.DATASET_FINAL;

SELECT COUNT(*)
FROM CARLOS_SANDBOX.DATAFEEDS.VW_DATASET_FINAL;

--verificando que la calidad se mantiene
SELECT
  SUM(IFF(TITLE IS NULL, 1, 0)) AS null_title,
  SUM(IFF(SUB_CATEGORY IS NULL, 1, 0)) AS null_sub_category,
  SUM(IFF(ESTIMATED_VIEWS IS NULL, 1, 0)) AS null_views,
  SUM(IFF(ESTIMATED_PURCHASES IS NULL, 1, 0)) AS null_purchases
FROM CARLOS_SANDBOX.DATAFEEDS.DATASET_FINAL;

--verificando que no haya anomalias
SELECT COUNT(*) AS anomalias
FROM CARLOS_SANDBOX.DATAFEEDS.DATASET_FINAL
WHERE ESTIMATED_PURCHASES > ESTIMATED_VIEWS;
